/*

 Media Mail, Issue #2 by Randall Bruder
 
 VARIOUS REQUIRED FIXES
 ----------------------
 
 RUN THIS IN TERMINAL TO FIND THE COM PORT NAME:
 ls /dev/tty.*
 
 OLDER COMPATIBLE VERSION OF librxtxSerial.jnilib:
 http://blog.iharder.net/2009/08/18/rxtx-java-6-and-librxtxserial-jnilib-on-intel-mac-os-x/ (https://archive.st/p9ki)
 PUT THE FILE HERE: Processing.app/Contents/Java/modes/java/libraries/serial/library/macosx/
 
 FIX FOR THE PortInUseException ERROR:
 http://jgrasstechtips.blogspot.com/2008/04/rxtx-and-funky-portinuseexception-on.html (https://archive.st/6vka)
 basically, run in terminal:
 sudo mkdir /var/lock && sudo chmod 777 /var/lock
 
 PRINTER PAPER:
 https://www.sparkfun.com/products/10560 (https://archive.st/3zc5)
 
 Pin Connections:
 ----------------
 
 [PRINTER]  [USB/TTY]
 BLACK      BLACK
 YELLOW     GREEN
 GREEN      WHITE
 
 Thanks to:
 ----------
 
 ThermalPrinter taken from http://www.openprocessing.org/sketch/66707
 @author Bruno Blazinc
 
 */

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import gnu.io.CommPortIdentifier;
import gnu.io.SerialPort;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;

import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Enumeration;

import java.util.StringTokenizer;

import processing.serial.*;

// Set up new printer object
Thermal printer = new Thermal(19200, "/dev/tty.usbserial-14410");

PrintWriter outputToFile;

int printerDelay = 500;

void setup() {
  //For some reason, the underline option wants to be on by default.
  printer.underlineOff();

  printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("================================");
delay(printerDelay);
printer.println("      ___  __");
delay(printerDelay);
printer.println("|\\/| |__  |  \\ |  /\\");
delay(printerDelay);
printer.println("|  | |___ |__/ | /~~\\");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("|\\/|  /\\  | |");
delay(printerDelay);
printer.println("|  | /~~\\ | |___");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("================================");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("(1) MEDIA MAIL ISSUE #2    $0.00");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("    TAX                    $0.00");
delay(printerDelay);
printer.println("    TOTAL                  $0.00");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("This is going to be something a");
delay(printerDelay);
printer.println("little different, and not what I");
delay(printerDelay);
printer.println("had originally planned for issue");
delay(printerDelay);
printer.println("2. With the current pandemic");
delay(printerDelay);
printer.println("situation happening, the");
delay(printerDelay);
printer.println("traditional production processes");
delay(printerDelay);
printer.println("I would use are unavailable. I'm");
delay(printerDelay);
printer.println("limited to making what I can");
delay(printerDelay);
printer.println("with the supplies I already have");
delay(printerDelay);
printer.println("in my apartment.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("And I only have one printer.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("              ----");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("But limitations make better");
delay(printerDelay);
printer.println("designers. So until such a time");
delay(printerDelay);
printer.println("as I can have access to better");
delay(printerDelay);
printer.println("printers, here's a black and");
delay(printerDelay);
printer.println("white, 32 characters wide, ASCII");
delay(printerDelay);
printer.println("only second issue of Media Mail.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Playing off the idea of receipt,");
delay(printerDelay);
printer.println("what follows is a selection of");
delay(printerDelay);
printer.println("interesting things I've taken");
delay(printerDelay);
printer.println("receipt of in the last month.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 1");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("   .------------------------.");
delay(printerDelay);
printer.println("  / 7:06 \\------------/ ==-- \\");
delay(printerDelay);
printer.println(" |             .-.            |");
delay(printerDelay);
printer.println(" |            (   )           |");
delay(printerDelay);
printer.println("||             `-'            |");
delay(printerDelay);
printer.println(" |           Chris >          ||");
delay(printerDelay);
printer.println("||                            ||");
delay(printerDelay);
printer.println("||      .-----------------.   ||");
delay(printerDelay);
printer.println(" |     (                   )  |");
delay(printerDelay);
printer.println("||      `-----------------'\\  |");
delay(printerDelay);
printer.println("||   .-----------.            |");
delay(printerDelay);
printer.println(" |  (             )           |");
delay(printerDelay);
printer.println(" |  /`-----------'            |");
delay(printerDelay);
printer.println(" |   .---------------.        |");
delay(printerDelay);
printer.println(" |  (                 )       |");
delay(printerDelay);
printer.println(" |  /`---------------'        |");
delay(printerDelay);
printer.println(" |                .-------.   |");
delay(printerDelay);
printer.println(" |               (         )  |");
delay(printerDelay);
printer.println(" |                `-------'\\  |");
delay(printerDelay);
printer.println(" |                            |");
delay(printerDelay);
printer.println("  \\        ----------        /");
delay(printerDelay);
printer.println("   .-------------.----------'");
delay(printerDelay);
printer.println("  (               )");
delay(printerDelay);
printer.println("  /`-------------'");
delay(printerDelay);
printer.println("            .---------------.");
delay(printerDelay);
printer.println("           (                 )");
delay(printerDelay);
printer.println("            `---------------'\\");
delay(printerDelay);
printer.println("            .-----------------.");
delay(printerDelay);
printer.println("           (                   )");
delay(printerDelay);
printer.println("            `-----------------'\\");
delay(printerDelay);
printer.println(" .-------------------.");
delay(printerDelay);
printer.println("(                     )");
delay(printerDelay);
printer.println("/`-------------------'");
delay(printerDelay);
printer.println(" .---------.");
delay(printerDelay);
printer.println("(           )");
delay(printerDelay);
printer.println("/`---------'");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("TAKEN RECEIPT OF:");
delay(printerDelay);
printer.println("-----------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Advice from a friend on the");
delay(printerDelay);
printer.println("frame color another friend");
delay(printerDelay);
printer.println("would be");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("May 16th, 2020");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 2");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("           Messages");
delay(printerDelay);
printer.println("            Chris >");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                           RANDY");
delay(printerDelay);
printer.println("       Do you remember what your");
delay(printerDelay);
printer.println("      manifesto was from school?");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("       and question that I swear");
delay(printerDelay);
printer.println("          is related to the last");
delay(printerDelay);
printer.println("         one: what kind of frame");
delay(printerDelay);
printer.println("                   color is Joe?");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("CHRIS");
delay(printerDelay);
printer.println("Oh god, no. But I searched");
delay(printerDelay);
printer.println("in Dropbox and I have an");
delay(printerDelay);
printer.println("indesign file. I just need");
delay(printerDelay);
printer.println("to grab my computer");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("I think Joe would be a");
delay(printerDelay);
printer.println("natural frame color. Like");
delay(printerDelay);
printer.println("a light-medium wood");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("I'm sure my manifesto is");
delay(printerDelay);
printer.println("garbage");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("It's downloading");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("               I mean this is my");
delay(printerDelay);
printer.println("                      manifesto:");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                  INTERNAL ERROR");
delay(printerDelay);
printer.println("           [58c2b3b4] 2020-05-16");
delay(printerDelay);
printer.println("       23:15:59: Fatal exception");
delay(printerDelay);
printer.println("             of type MWException");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("        so the bar is pretty low");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("hahaha");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("So weird reading this");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("       I felt the same way about");
delay(printerDelay);
printer.println("                   reading Joe's");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("      like there's actually some");
delay(printerDelay);
printer.println("       really good advice in it,");
delay(printerDelay);
printer.println("             that I can take now");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 3");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("    .-----------------------.");
delay(printerDelay);
printer.println("   (                         )");
delay(printerDelay);
printer.println("    `-----------------------'");
delay(printerDelay);
printer.println("       |                ||");
delay(printerDelay);
printer.println("       |                ||");
delay(printerDelay);
printer.println("       |                ||");
delay(printerDelay);
printer.println("       |                ||");
delay(printerDelay);
printer.println("       |                ||");
delay(printerDelay);
printer.println("       |                ||");
delay(printerDelay);
printer.println("       |                ||");
delay(printerDelay);
printer.println("       |                ||");
delay(printerDelay);
printer.println("       |                ||");
delay(printerDelay);
printer.println("       |                ||");
delay(printerDelay);
printer.println("       |                ||");
delay(printerDelay);
printer.println("      .+----------------+.");
delay(printerDelay);
printer.println("     | |                | )|");
delay(printerDelay);
printer.println("     |`------------------'||");
delay(printerDelay);
printer.println("     |                    ||");
delay(printerDelay);
printer.println("     |                    ||");
delay(printerDelay);
printer.println("     |         .-.        ||");
delay(printerDelay);
printer.println("     |        ( 3 )       ||");
delay(printerDelay);
printer.println("     |         `-'        ||");
delay(printerDelay);
printer.println("     |                    ||");
delay(printerDelay);
printer.println("     |         .-.        ||");
delay(printerDelay);
printer.println("     |        ( 2 )       ||");
delay(printerDelay);
printer.println("     |         `-'        ||");
delay(printerDelay);
printer.println("     |                    ||");
delay(printerDelay);
printer.println("     |         .-.        ||");
delay(printerDelay);
printer.println("   --|        ( 1 )       |+-");
delay(printerDelay);
printer.println("  /  |         `-'        || \\");
delay(printerDelay);
printer.println(" /   |                    ||  \\");
delay(printerDelay);
printer.println("|    |                    )    |");
delay(printerDelay);
printer.println(" \\    `------------------'    /");
delay(printerDelay);
printer.println("  \\                          /");
delay(printerDelay);
printer.println("   \\-+--------------------+-/");
delay(printerDelay);
printer.println("     |                    ||");
delay(printerDelay);
printer.println("      `------------------'");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("TAKEN RECEIPT OF:");
delay(printerDelay);
printer.println("-----------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Instructions for making an iced");
delay(printerDelay);
printer.println("oat milk latte without any");
delay(printerDelay);
printer.println("espresso equipment.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("April 22nd, 2020");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 4");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Equipment/Ingredients:");
delay(printerDelay);
printer.println("----------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("* AeroPress");
delay(printerDelay);
printer.println("* 18 grams of coffee");
delay(printerDelay);
printer.println("* coffee grinder (that can grind");
delay(printerDelay);
printer.println("  at a generally fine size)");
delay(printerDelay);
printer.println("* Oatly Barista Edition");
delay(printerDelay);
printer.println("* Ice");
delay(printerDelay);
printer.println("* Scale");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Steps:");
delay(printerDelay);
printer.println("------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("* Invert the AeroPress (pushing");
delay(printerDelay);
printer.println("  the plunger into the top of");
delay(printerDelay);
printer.println("  the brew chamber.)");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("* Put a filter in the filter cap");
delay(printerDelay);
printer.println("  and rinse it with hot water");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("* Add 18g of finely ground");
delay(printerDelay);
printer.println("  coffee. About as fine as a");
delay(printerDelay);
printer.println("  non-espresso griner can go");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("* Add 90g of water just off");
delay(printerDelay);
printer.println("  boiling");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("* Stir with a spoon, a little");
delay(printerDelay);
printer.println("  bit aggressively to get all");
delay(printerDelay);
printer.println("  grounds wet and break up");
delay(printerDelay);
printer.println("  any clumps");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("* Attach cap and filter, let");
delay(printerDelay);
printer.println("  steep for 90 seconds");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("* Invert the AeroPress, swirl to");
delay(printerDelay);
printer.println("  settle the grounds, wait a few");
delay(printerDelay);
printer.println("  seconds, then plunge slowly");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("* You'll get 70g of a strong");
delay(printerDelay);
printer.println("  coffee concentrate, pour it");
delay(printerDelay);
printer.println("  over a glass of ice and Oatly");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("* Enjoy");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 5");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("         .-----------.");
delay(printerDelay);
printer.println("     _.-'             `--.");
delay(printerDelay);
printer.println("   ,'                     `.");
delay(printerDelay);
printer.println(" ,'   .---------------.     `.");
delay(printerDelay);
printer.println(";                      '-.    :");
delay(printerDelay);
printer.println("|      .-------------.        |*");
delay(printerDelay);
printer.println("|                     '-.     |*");
delay(printerDelay);
printer.println(":     .-------------.         ;*");
delay(printerDelay);
printer.println(" \\                   `.      /**");
delay(printerDelay);
printer.println("  `.                       ,'**");
delay(printerDelay);
printer.println("    `.                   ,'***");
delay(printerDelay);
printer.println("      `--.           _.-' **");
delay(printerDelay);
printer.println("       ***`---------'*****");
delay(printerDelay);
printer.println("           ***********");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("               X");
delay(printerDelay);
printer.println("              / \\");
delay(printerDelay);
printer.println("             /   \\");
delay(printerDelay);
printer.println("            /     \\");
delay(printerDelay);
printer.println("           /       \\");
delay(printerDelay);
printer.println("          /         \\");
delay(printerDelay);
printer.println("         /           \\");
delay(printerDelay);
printer.println("        +---+     +---+");
delay(printerDelay);
printer.println("            |     |");
delay(printerDelay);
printer.println("    ________|_____|_________");
delay(printerDelay);
printer.println("   /        |     |         \\");
delay(printerDelay);
printer.println("  /         |     |          \\");
delay(printerDelay);
printer.println(" /__________|_____|___________\\");
delay(printerDelay);
printer.println("|\\__________|_____|___________/|");
delay(printerDelay);
printer.println("|                              |");
delay(printerDelay);
printer.println("|                              |");
delay(printerDelay);
printer.println("|   ________________________   |");
delay(printerDelay);
printer.println("|  /                        \\  |");
delay(printerDelay);
printer.println("| /                          \\ |");
delay(printerDelay);
printer.println("|/                            \\|");
delay(printerDelay);
printer.println("|______________________________|");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("TAKEN RECEIPT OF:");
delay(printerDelay);
printer.println("-----------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("An email from someone trying");
delay(printerDelay);
printer.println("to get their song on a Spotify");
delay(printerDelay);
printer.println("playlist I made that only has");
delay(printerDelay);
printer.println("177 followers");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("April 25th, 2020");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 6");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Jenny Lindfors");
delay(printerDelay);
printer.println("<jenny@thisissailingstones.com>");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("TO: hello@randallbruder.com");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("DATE: Apr 25, 2020, 12:35 PM");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("SUBJECT: A song for you?");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println(">>: Important according to");
delay(printerDelay);
printer.println("    Google magic.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Hi Randall,");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("You don't know me but I really");
delay(printerDelay);
printer.println("like your Women & Indie Folk");
delay(printerDelay);
printer.println("playlist on Spotify. It features");
delay(printerDelay);
printer.println("some of my fave artists (Marika");
delay(printerDelay);
printer.println("Hackman, Alela Diane) and some");
delay(printerDelay);
printer.println("friends of mine (Mesadorm).");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("I wanted to share this record");
delay(printerDelay);
printer.println("of mine with you, which came");
delay(printerDelay);
printer.println("out on Friday.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("This song in particular I");
delay(printerDelay);
printer.println("thought you might like, a solo");
delay(printerDelay);
printer.println("acoustic sad song called \"Joe\"");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("https://open.spotify.com/track/");
delay(printerDelay);
printer.println("1CU9yuhR1012oCm1FuTDfN");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("If you get a chance to listen");
delay(printerDelay);
printer.println("that would be amazing!");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("All the best");
delay(printerDelay);
printer.println("Jenny");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("---");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("www.thisissailingstones.com");
delay(printerDelay);
printer.println("www.khlrecords.com");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("(the email went unanswered)");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 7");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("          .----------.");
delay(printerDelay);
printer.println("        ,'       `.\\ \\`.");
delay(printerDelay);
printer.println("       ;    ------ : ---:");
delay(printerDelay);
printer.println("       |--- ------ | ---|");
delay(printerDelay);
printer.println("       |---  ----- | ---|");
delay(printerDelay);
printer.println("       :---  ----- ; ---;");
delay(printerDelay);
printer.println("        \\---  ----/ ---/");
delay(printerDelay);
printer.println("         `.     ,'/ /,'");
delay(printerDelay);
printer.println("          /`---'----'|");
delay(printerDelay);
printer.println("         / |         |");
delay(printerDelay);
printer.println("        /  +---+-+---+");
delay(printerDelay);
printer.println("       /       | |");
delay(printerDelay);
printer.println("       |       | |");
delay(printerDelay);
printer.println("       |       | |");
delay(printerDelay);
printer.println("        \\      | |");
delay(printerDelay);
printer.println("         \\     | |");
delay(printerDelay);
printer.println("          \\    | |");
delay(printerDelay);
printer.println("           \\   | |");
delay(printerDelay);
printer.println("            \\  | |");
delay(printerDelay);
printer.println("             \\ | |");
delay(printerDelay);
printer.println("              \\| |");
delay(printerDelay);
printer.println("               | |");
delay(printerDelay);
printer.println("               | |\\");
delay(printerDelay);
printer.println("               | | \\");
delay(printerDelay);
printer.println("               | |  \\");
delay(printerDelay);
printer.println("               | |   \\");
delay(printerDelay);
printer.println("               | |    \\");
delay(printerDelay);
printer.println("               | |     |");
delay(printerDelay);
printer.println("               | |     |");
delay(printerDelay);
printer.println("               | |    /");
delay(printerDelay);
printer.println("               | |   /");
delay(printerDelay);
printer.println("               | |  /");
delay(printerDelay);
printer.println("               | | /");
delay(printerDelay);
printer.println("               | |/");
delay(printerDelay);
printer.println("         .-----+ +-----.");
delay(printerDelay);
printer.println("       ,'      | |      `.");
delay(printerDelay);
printer.println("      (        +-+        )");
delay(printerDelay);
printer.println("       '-.             ,-'");
delay(printerDelay);
printer.println("          `-----------'");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("TAKEN RECEIPT OF:");
delay(printerDelay);
printer.println("-----------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Five jokes solicited");
delay(printerDelay);
printer.println("from friends");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("May 21st-22nd, 2020");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 8");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("> What type of car would a");
delay(printerDelay);
printer.println("  Viking drive?");
delay(printerDelay);
printer.println("> A Fjord Explorer");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                     -Sam Bunner");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("> Cual es el animal mas flojo");
delay(printerDelay);
printer.println("  en todo el mundo?");
delay(printerDelay);
printer.println("> Cual?");
delay(printerDelay);
printer.println("> El pez.");
delay(printerDelay);
printer.println("> Por que?");
delay(printerDelay);
printer.println("> Que hace el pez?");
delay(printerDelay);
printer.println("> Nada.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                 -Billy Greenman");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("> What's 2 + 2?");
delay(printerDelay);
printer.println("> What?");
delay(printerDelay);
printer.println("> 4!");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("              -Stephanie Anstett");
delay(printerDelay);
printer.println("(Joe explains: \"Math is a joke");
delay(printerDelay);
printer.println("to Stephanie.\")");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("> Why does the Norway Navy");
delay(printerDelay);
printer.println("  have barcodes on the side of");
delay(printerDelay);
printer.println("  their ships?");
delay(printerDelay);
printer.println("> So when they come back to");
delay(printerDelay);
printer.println("  port, they can Scandanavian");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("               -Chris Masouredis");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("> What the the old man say when");
delay(printerDelay);
printer.println("  someone stole his car?");
delay(printerDelay);
printer.println("> Damnit, someone stole my car!");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                   -Geoff Dicks");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 9");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("     .--------------------.");
delay(printerDelay);
printer.println(" _.-'                      `--.");
delay(printerDelay);
printer.println("|                              |");
delay(printerDelay);
printer.println("|                              |");
delay(printerDelay);
printer.println("|                              |");
delay(printerDelay);
printer.println("|                              |");
delay(printerDelay);
printer.println("|                      -hmMMh+.|");
delay(printerDelay);
printer.println("|                      +MMMNo  |");
delay(printerDelay);
printer.println("|                    ``ydmd`   |");
delay(printerDelay);
printer.println("|               `-+sydmMMNo    |");
delay(printerDelay);
printer.println("|             -smMMMMMMMMM+    |");
delay(printerDelay);
printer.println("|y+-.`      -yNMMMMMMMMMMM:    |");
delay(printerDelay);
printer.println("|sdNNdyo:.-yNMMMMMMMMMMMMM.    |");
delay(printerDelay);
printer.println("| `-+hmMMNNMMMMMMMMMMMMMMN     |");
delay(printerDelay);
printer.println("|     .:ymMMMMMMMMMMMMMMm:     |");
delay(printerDelay);
printer.println("|        `sMMmmNNMMMMMm+`      |");
delay(printerDelay);
printer.println("|        .y/.````.--:d+        |");
delay(printerDelay);
printer.println("|       :o           `/+       |");
delay(printerDelay);
printer.println("|      .o+-`          `o--`    |");
delay(printerDelay);
printer.println("|                              |");
delay(printerDelay);
printer.println("|                              |");
delay(printerDelay);
printer.println("|     .-. .-. .-. . . . .-. .-.|");
delay(printerDelay);
printer.println("|     |(  |(  |-  | | | |-  |( |");
delay(printerDelay);
printer.println("|     `-' ' ' `-' `.'.' `-' ' '|");
delay(printerDelay);
printer.println("|       .-. .-. .-. .-. .-. . .|");
delay(printerDelay);
printer.println("|       |-  |-|  |  `-. |-| |\\||");
delay(printerDelay);
printer.println("|       '   ` ' `-' `-' ` ' ' `|");
delay(printerDelay);
printer.println("|                              |");
delay(printerDelay);
printer.println("|                              |");
delay(printerDelay);
printer.println(" `.                          ,'");
delay(printerDelay);
printer.println("   `---.                _.--'");
delay(printerDelay);
printer.println("     `--`--------------'.-'");
delay(printerDelay);
printer.println("         `------------'");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("TAKEN RECEIPT OF:");
delay(printerDelay);
printer.println("-----------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Six cans of beer from Brewery");
delay(printerDelay);
printer.println("Faisan in the Islandview");
delay(printerDelay);
printer.println("neighborhood of Detroit (via");
delay(printerDelay);
printer.println("contanctless pick-up), paired");
delay(printerDelay);
printer.println("with reviews taken from");
delay(printerDelay);
printer.println("stangers online");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("April 28th, 2020");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 10");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("3 x Night Heron (Coffee Stout)");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Coffee forward but the coffee");
delay(printerDelay);
printer.println("is not overpowering. Retains");
delay(printerDelay);
printer.println("some malty sweetness (3/5)");
delay(printerDelay);
printer.println("                        -Ryan F.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Legit coffee stout. Espresso");
delay(printerDelay);
printer.println("like.chocolate. finishes dry.");
delay(printerDelay);
printer.println("a bit nutty and slightest of");
delay(printerDelay);
printer.println("maybe fruit/citrus from the java");
delay(printerDelay);
printer.println("selection (4.25/5)");
delay(printerDelay);
printer.println("                      -Jeremy G.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("2 x Quiddity (Witbier)");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Great porch sipper, even if the");
delay(printerDelay);
printer.println("day was a bit cold and windy!");
delay(printerDelay);
printer.println("(4/5)");
delay(printerDelay);
printer.println("                     -Kendall J.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("The aroma alone transports me");
delay(printerDelay);
printer.println("straight to summer-time. A");
delay(printerDelay);
printer.println("perfect Belgian Wit. (4.25/5)");
delay(printerDelay);
printer.println("                     -T Wasinski");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("1 x Periphery (Raspberry Saison)");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("This is one of the best saisons");
delay(printerDelay);
printer.println("I've ever had, no bullshit");
delay(printerDelay);
printer.println("(4.5/5)");
delay(printerDelay);
printer.println("                       -Tyler M.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Not very Rasberry-y (3.25/5)");
delay(printerDelay);
printer.println("                       -Aaron H.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("Ok, hint of medicine flavor that");
delay(printerDelay);
printer.println("you get with the berry beers");
delay(printerDelay);
printer.println("sometimes (4/5)");
delay(printerDelay);
printer.println("                       -Linda H.");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 11");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("--------------------------------");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("           NO REFUNDS");
delay(printerDelay);
printer.println("          NO EXCHANGES");
delay(printerDelay);
printer.println("           NO RETURNS");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("    Appendices available on:");
delay(printerDelay);
printer.println("     https://mediamail.work");
delay(printerDelay);
printer.println("");
delay(printerDelay);
printer.println("                       pg. 12");
delay(printerDelay);
printer.println("--------------------------------");

  printer.feed(8);
  exit();
}
